FROM nginx

RUN mkdir /usr/share/elasticsearch
WORKDIR /usr/share/elasticsearch
RUN curl --retry 10 -S -L --output /usr/share/elasticsearch/elasticsearch.tar.gz https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.10.0-linux-x86_64.tar.gz
RUN tar -zxf /usr/share/elasticsearch/elasticsearch.tar.gz --strip-components=1
COPY ./geoip-packages/ /usr/share/nginx/html/
RUN /usr/share/elasticsearch/bin/elasticsearch-geoip -s /usr/share/nginx/html/ -t /usr/share/nginx/html/
WORKDIR /
RUN rm -rf /usr/share/elasticsearch
