---
tarball_dir: "/usr/local"
rke2_channel: stable
audit_policy_config_file_path: ""
registry_config_file_path: ""
add_iptables_rules: false
rke2_common_yum_repo:
  name: rke2-common
  description: "Rancher RKE2 Common Latest"
  baseurl: "https://rpm.rancher.io/rke2/latest/common/centos/$releasever/noarch"
  gpgcheck: true
  gpgkey: "https://rpm.rancher.io/public.key"
  enabled: yes

rke2_versioned_yum_repo:
  name: "rke2-v{{ rke2_version_majmin }}"  # noqa var-spacing
  description: "Rancher RKE2 Version"
  baseurl: "https://rpm.rancher.io/rke2/latest/{{ rke2_version_majmin }}/centos/$releasever/$basearch"
  gpgcheck: true
  gpgkey: "https://rpm.rancher.io/public.key"
  enabled: yes

rke2_config: {}
