apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: prod
spec:
  version: 8.9.0
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: monitor
          namespace: monitor
    logs:
      elasticsearchRefs:
        - name: monitor
          namespace: monitor
  nodeSets:
  - name: prod
    count: 3
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            securityContext:
              seccompProfile:
                type: RuntimeDefault
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
              runAsNonRoot: true
          - name: filebeat
            securityContext:
              seccompProfile:
                type: RuntimeDefault
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
          - name: metricbeat
            securityContext:
              seccompProfile:
                type: RuntimeDefault
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
        initContainers:
          - name: elastic-internal-init-filesystem
            securityContext:
              seccompProfile:
                type: RuntimeDefault
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
              runAsNonRoot: true
          - name: elastic-internal-suspend
            securityContext:
              seccompProfile:
                type: RuntimeDefault
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
              runAsNonRoot: true
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn
    config:
      node.store.allow_mmap: false
      xpack.ml.model_repository: http://elser.repo.svc.cluster.local
      ingest.geoip.downloader.endpoint: http://geoip-mirror.repo.svc.cluster.local
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: prod
spec:
  version: 8.9.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: monitor
          namespace: monitor
    logs:
      elasticsearchRefs:
        - name: monitor  
          namespace: monitor  
  podTemplate:
    spec:
      containers:
        - name: kibana
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
        - name: filebeat
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
        - name: metricbeat
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
      initContainers:
        - name: elastic-internal-init-config
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
  config:
    map.emsUrl: "https://maps.air-gap.demo"
    xpack.fleet.registryUrl: "http://elastic-package-registry.repo.svc.cluster.local"
    xpack.fleet.agents.elasticsearch.hosts: ["https://elasticsearch-es-http.prod.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-agent-http.prod.svc:8220"]
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: eck-fleet-server
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
        - name: fleet_server-1
          id: fleet_server-1
          package:
            name: fleet_server
      - name: Elastic Agent on ECK policy
        id: eck-agent
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        is_default: true
        package_policies:
          - name: system-1
            id: system-1
            package:
              name: system
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-ingress
  namespace: prod
  annotations:
    cert-manager.io/cluster-issuer: "ca-issuer"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "false" 
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" 
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - prod.air-gap.demo
    secretName: monitor-tls
  rules:
  - host: prod.air-gap.demo
    http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: kibana-kb-http 
              port:
                number: 5601