---

- name: Check if rke2-server is previously installed
  ansible.builtin.debug:
    msg: "rke2-server is already installed. Skipping installation steps."
  when: >
    ansible_facts.services["rke2-server.service"] is defined
    and not ansible_facts.services["rke2-server.service"].status == 'disabled'

- name: Set fact if rke2-server was previously installed
  set_fact:
    installed: true
  when: >
    ansible_facts.services["rke2-server.service"] is defined
    and not ansible_facts.services["rke2-server.service"].status == 'disabled'

- name: Check if rke2-agent is previously installed
  ansible.builtin.debug:
    msg: "rke2-agent is already installed. Skipping installation steps."
  when: >
    ansible_facts.services["rke2-agent.service"] is defined
    and not ansible_facts.services["rke2-agent.service"].status == 'disabled'

- name: Set fact if rke2-agent was previously installed
  set_fact:
    installed: true
  when: >
    ansible_facts.services["rke2-agent.service"] is defined
    and not ansible_facts.services["rke2-agent.service"].status == 'disabled'
